# Generated by Django 6.0.4 on 2026-05-10 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuario_data_de_nascenca_usuario_telefone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='data_de_nascenca',
            new_name='date_of_birth',
        ),
    ]
