# Generated by Django 6.0.4 on 2026-05-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_data_de_nascenca_usuario_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
