# Generated by Django 6.0.4 on 2026-04-29 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalo_horas', models.PositiveIntegerField()),
                ('horario_inicial', models.TimeField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('pausado', 'Pausado'), ('finalizado', 'Finalizado')], default='ativo', max_length=20)),
                ('medicamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tratamento', to='medications.medicamento')),
            ],
        ),
    ]
