# Generated by Django 6.0.4 on 2026-04-29 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_planejado', models.DateTimeField()),
                ('horario_real', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('tomado', 'Tomado'), ('perdido', 'Perdido')], default='pendente', max_length=20)),
                ('recalculada', models.BooleanField(default=False)),
                ('tratamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='treatments.tratamento')),
            ],
            options={
                'ordering': ['horario_planejado'],
            },
        ),
    ]
